reddit:
  client:
    clientId: ***REMOVED***
    clientSecret: ***REMOVED***
    accessTokenUri: https://www.reddit.com/api/v1/access_token
    userAuthorizationUri: https://www.reddit.com/api/v1/authorize
    scope: identity
    clientAuthenticationScheme: header
    preEstablishedRedirectUri: http://localhost:8080/login
    useCurrentUri: false
  resource:
    userInfoUri: https://oauth.reddit.com/api/v1/me