security:
  oauth2:
    client:
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      accessTokenUri: https://discordapp.com/api/oauth2/token
      userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://discordapp.com/api/users/@me