discord:
  client:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    accessTokenUri: https://discordapp.com/api/oauth2/token
    userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
    scope: identify
    clientAuthenticationScheme: query
  resource:
    userInfoUri: https://discordapp.com/api/users/@me