security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://discordapp.com/api/oauth2/token
      userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
      scope: identify
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://discordapp.com/api/users/@me
#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
logging:
  level:
    org.springframework.security: DEBUG