reddit:
  client:
    clientId: ***REMOVED***
    clientSecret: ***REMOVED***
    accessTokenUri: https://www.reddit.com/api/v1/access_token
    userAuthorizationUri: https://www.reddit.com/api/v1/authorize
    scope: identity
    clientAuthenticationScheme: header
    preEstablishedRedirectUri: http://localhost:8080/loginReddit
    useCurrentUri: false
  resource:
    userInfoUri: https://oauth.reddit.com/api/v1/me
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver